### ISSUE TITLE
No icon shown for BBB-Blugin

### ISSUE THREAD

**Issue by afle** [blindsidenetworks/mattermost-plugin-bigbluebutton#111]
Hi,

we are running Mattermost 5.25.3. The BBB-plugin is installed and configured. But there is no icon for starting a conference shown anymore.
Using the slash command "/bbb" creates just following message

---------------
#BigBlueButton #Big Blue Button Meeting #ID1hUXv8sYWka64zPZx26tNjIwzvi
---------------

Each hashtagged word is a link to "https://<FQDN of mattermost server>/<team>/messages/@<channel>#". The last string is not the secret key of BBB. I have no idea, what it is. 

Why does this plugin creates such a invalid link?

Thanks

**Comment by IdrissHassani11** [comment]
Hello, I'm having this issue too 
the join button appears correctly when we use Mattermost Classic version... But on the newer version of the app there's the weird link with #ID something.

**Comment by OneTwoBarbecue** [comment]
Hi, 
same problem here (server version 5.23.0). I guess the classic app just runs a webbrowser which accesses the mobile version of the webinterface and because of that the bbb-plugin works correctly. 
But unfortunately the native mattermost-app causes the issue and does not permit any member to participate in the conference but creates the message shown above. 
So does the issue need to be fixed on the mattermost-app-side or on the bbb-plugin-side?
Kind regards, Marco

**Comment by harshilsharma63** [comment]
@afle by the description of the error, I'm guessing you're getting this on the Mattermost mobile app? If that's the case, then, unfortunately, you cannot use this plugin on Mattermost mobile app. It's a limitation on Mattermost side and nothing the plugin can do.

If it;'s on the webapp side, then you should be getting some errors in your browser console. If you could share those, it would help in debugging.

**Comment by harshilsharma63** [comment]
@afle any update on this?

**Comment by harshilsharma63** [comment]
@afle I'm closing this one for now. If you face the issue on the desktop browser or the Mattermost desktop app, feel free to re-open this.
