### ISSUE TITLE
Unable to find recordings on mattermost bigbluebutton plugin

### ISSUE THREAD

**Issue by EbsrVlee** [blindsidenetworks/mattermost-plugin-bigbluebutton#18]
Hello,

I have the big blue button plugin added to mattermost by following these instructions ( https://github.com/blindsidenetworks/mattermost-plugin-bigbluebutton )
However, when I record a session I cannot find it afterwards. (Recording without audio)
When I click on View Recordings it is empty.

Please advise.
Thank you.

**Comment by ffdixon** [comment]
Are you using your own BigBlueButton server or test-install?

**Comment by ffdixon** [comment]
Got it -- we'll take a closer look.

**Comment by EbsrVlee** [comment]
Thank you. :)

**Comment by EbsrVlee** [comment]
Hello, 
Any news about this?

**Comment by Bortseb** [comment]
I am having the same issue, but with my own bbb server.

This is all I see after a meeting with a recording is ended:
![image](https://user-images.githubusercontent.com/1617130/52975297-fb8bdd80-3392-11e9-835b-7c3e6569a25f.png)

I just set this all up today.

**Comment by Bortseb** [comment]
Hmmm, seems they did eventually appear, it just took a long while.

**Comment by eyebank** [comment]
Experiencing the same issue with recordings not showing up. We built another server from scratch recordings don show up. Is there a way we can check to see if recordings are sitting on the bbb server anywhere?

**Comment by eyebank** [comment]
> I am having the same issue, but with my own bbb server.
> 
> This is all I see after a meeting with a recording is ended:
> ![image](https://user-images.githubusercontent.com/1617130/52975297-fb8bdd80-3392-11e9-835b-7c3e6569a25f.png)
> 
> I just set this all up today.

@Bortseb did you get this issue 
resolved?

**Comment by a3nm** [comment]
Same issue here -- with our Mattermost and BBB install (Mattermost Enterprise Edition Version: 5.21.0 from Docker, BigBlueButton Client Build 862, and BigBlueButton plugin for Mattermost version 2.1.0), when recording a session and then ending it, no recordings are ever posted to the channel (and clicking "View recordings" does not show anything), even several days after the meeting.

**Comment by mathieu-rossignol** [comment]
Hi there, +1: on our own mattermost+bbb installations, we can record meetings but we don't find them afterwards.

mattermost:Mattermost Version: 5.25.3
Database Schema Version: 5.25.0
Database: postgres

**Comment by mathieu-rossignol** [comment]
Ok regarding the problem I just described, the problem seems to be on the bbb server where the services in charge of the processing of the recordings before publication are not all running. This is probably the root cause of our recordings not published on mattermost. So I will investigate my services now. I let these statements for other people that could come here for the same problems. I confess I had a poor understanding of the architecture bbb+ui with greenlight, after investigations now I better understand (I did not installed our bbb/greenlight server). I found the problem running the 'bbb-record --list' command expplained on the documentation I pointed to in my last post. See the failing services responsible for performing the phases up to the publication of the recordings, only the Process one is running...:
![image](https://user-images.githubusercontent.com/18575218/98387196-65f61d00-2051-11eb-84dc-f56fb9a63d7e.png)
Yellow ones seem to have problem with file/directories existence or permissions....

**Comment by andzejsp** [comment]
Im having the same problem.. Looks like they dropped the support for bbb

**Comment by harshilsharma63** [comment]
@andzejsp @a3nm can you verify that SiteURL is correctly set in Mattermost config?

**Comment by a3nm** [comment]
Unfortunately after 1.5 years the Mattermost instance in question no longer exists, so I am unable to provide further input on trying to reproduce this issue. Thanks nevertheless!

**Comment by andzejsp** [comment]
Yes URL was correct and now since its been a long time since I have posted the issue i cant verify because we have moved on to different options. Thank you
